### ISSUE TITLE
Github Actions/Heroku Deployment

### ISSUE THREAD

**Issue by jofftiquez** [antonioalmeida/ditado-api#20]
Hello this is not an issue actually, I just read on your README this:

> Github Actions had just came out and I wanted to learn all about it, namely how to automate deployments via Heroku. Fetching ditados seemed like the perfect excuse. Also inspired by this.

I just want to let you know that you can actually create automatic deployments in heroku even without github actions. That would be more way convenient. If you want to learn more about github action I suggest you can make some automated test, or some sort of thank you message for every issue. :)

**Comment by antonioalmeida** [comment]
Yes, I had already used the Heroku-Github feature directly but with Actions I have more control of the flow of execution. Also at the time the Heroku Action was fairly recent so not a single tutorial was actually working, so I did my own version. 

As for the automated tests or messages on issues, feel free to implement those 😄
