### ISSUE TITLE
Add endpoint to retrieve random entry

### ISSUE THREAD

**Issue by antonioalmeida** [antonioalmeida/ditado-api#5]
At the moment only the entire document can be fetched, but retrieving a random entry would be way more interesting.

I'm leaving this issue open on purpose because it it quite simple and a beginner might try and have a go at it.

**Comment by enzomzaocv** [comment]
Hi, how it is going? I'll be glad to contribute, please assign this issue to me.

**Comment by antonioalmeida** [comment]
Go ahead @enzomzaocv , let me know if you need help. I'll try and development instructions tomorrow
